DELETE FROM atsproject WHERE client='BT' AND project= '110003'
DELETE FROM agldimvalue WHERE client='BT' AND attribute_id='B0' AND dim_value= '110003'
DELETE FROM agldescription WHERE client='BT' AND attribute_id='B0' AND language='NO' AND dim_value= '110003'
DELETE FROM aglrelvalue WHERE client='BT' AND attribute_id='B0' AND att_value= '110003'
DELETE FROM afxprostyring WHERE client='BT' AND attribute_id='B0' AND dim_value= '110003'
DELETE FROM afxproadmin WHERE client='BT' AND attribute_id='B0' AND dim_value= '110003'
DELETE FROM atsinvinfo WHERE client='BT' AND attribute_id='B0' AND dim_value= '110003'
DELETE FROM atsactivity WHERE client='BT' AND project= '110003'
DELETE FROM atsproject WHERE client='BT' AND project= '110011'
DELETE FROM agldimvalue WHERE client='BT' AND attribute_id='B0' AND dim_value= '110011'
DELETE FROM agldescription WHERE client='BT' AND attribute_id='B0' AND language='NO' AND dim_value= '110011'
DELETE FROM aglrelvalue WHERE client='BT' AND attribute_id='B0' AND att_value= '110011'
DELETE FROM afxprostyring WHERE client='BT' AND attribute_id='B0' AND dim_value= '110011'
DELETE FROM afxproadmin WHERE client='BT' AND attribute_id='B0' AND dim_value= '110011'
DELETE FROM atsinvinfo WHERE client='BT' AND attribute_id='B0' AND dim_value= '110011'
DELETE FROM atsactivity WHERE client='BT' AND project= '110011'
DELETE FROM atsproject WHERE client='BT' AND project= '120002'
DELETE FROM agldimvalue WHERE client='BT' AND attribute_id='B0' AND dim_value= '120002'
DELETE FROM agldescription WHERE client='BT' AND attribute_id='B0' AND language='NO' AND dim_value= '120002'
DELETE FROM aglrelvalue WHERE client='BT' AND attribute_id='B0' AND att_value= '120002'
DELETE FROM afxprostyring WHERE client='BT' AND attribute_id='B0' AND dim_value= '120002'
DELETE FROM afxproadmin WHERE client='BT' AND attribute_id='B0' AND dim_value= '120002'
DELETE FROM atsinvinfo WHERE client='BT' AND attribute_id='B0' AND dim_value= '120002'
DELETE FROM atsactivity WHERE client='BT' AND project= '120002'
DELETE FROM atsworkorder WHERE client='BT' AND work_order= '110003100'
DELETE FROM agldimvalue WHERE client='BT' AND attribute_id='BF' AND dim_value= '110003100'
DELETE FROM agldescription WHERE client='BT' AND attribute_id='BF' AND language='NO' AND dim_value= '110003100'
DELETE FROM aglrelvalue WHERE client='BT' AND attribute_id='BF' AND att_value= '110003100'
DELETE FROM afxaofin WHERE client='BT' AND attribute_id='BF' AND dim_value= '110003100'
DELETE FROM afxaoegenfin WHERE client='BT' AND attribute_id='BF' AND dim_value= '110003100'
DELETE FROM afxaoindirekte WHERE client='BT' AND attribute_id='BF' AND dim_value= '110003100'
DELETE FROM atsinvinfo WHERE client='BT' AND attribute_id='BF' AND dim_value= '110003100'
DELETE FROM atsworkorder WHERE client='BT' AND work_order= '110003101'
DELETE FROM agldimvalue WHERE client='BT' AND attribute_id='BF' AND dim_value= '110003101'
DELETE FROM agldescription WHERE client='BT' AND attribute_id='BF' AND language='NO' AND dim_value= '110003101'
DELETE FROM aglrelvalue WHERE client='BT' AND attribute_id='BF' AND att_value= '110003101'
DELETE FROM afxaofin WHERE client='BT' AND attribute_id='BF' AND dim_value= '110003101'
DELETE FROM afxaoegenfin WHERE client='BT' AND attribute_id='BF' AND dim_value= '110003101'
DELETE FROM afxaoindirekte WHERE client='BT' AND attribute_id='BF' AND dim_value= '110003101'
DELETE FROM atsinvinfo WHERE client='BT' AND attribute_id='BF' AND dim_value= '110003101'
DELETE FROM atsworkorder WHERE client='BT' AND work_order= '110011100'
DELETE FROM agldimvalue WHERE client='BT' AND attribute_id='BF' AND dim_value= '110011100'
DELETE FROM agldescription WHERE client='BT' AND attribute_id='BF' AND language='NO' AND dim_value= '110011100'
DELETE FROM aglrelvalue WHERE client='BT' AND attribute_id='BF' AND att_value= '110011100'
DELETE FROM afxaofin WHERE client='BT' AND attribute_id='BF' AND dim_value= '110011100'
DELETE FROM afxaoegenfin WHERE client='BT' AND attribute_id='BF' AND dim_value= '110011100'
DELETE FROM afxaoindirekte WHERE client='BT' AND attribute_id='BF' AND dim_value= '110011100'
DELETE FROM atsinvinfo WHERE client='BT' AND attribute_id='BF' AND dim_value= '110011100'
DELETE FROM atsworkorder WHERE client='BT' AND work_order= '120002100'
DELETE FROM agldimvalue WHERE client='BT' AND attribute_id='BF' AND dim_value= '120002100'
DELETE FROM agldescription WHERE client='BT' AND attribute_id='BF' AND language='NO' AND dim_value= '120002100'
DELETE FROM aglrelvalue WHERE client='BT' AND attribute_id='BF' AND att_value= '120002100'
DELETE FROM afxaofin WHERE client='BT' AND attribute_id='BF' AND dim_value= '120002100'
DELETE FROM afxaoegenfin WHERE client='BT' AND attribute_id='BF' AND dim_value= '120002100'
DELETE FROM afxaoindirekte WHERE client='BT' AND attribute_id='BF' AND dim_value= '120002100'
DELETE FROM atsinvinfo WHERE client='BT' AND attribute_id='BF' AND dim_value= '120002100'
